[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[["
key = "["
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[]"
key = "]"
mods = "Alt"
