gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#b4befe"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#b4befe"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"

  authorColors:
    "*": "#b4befe"
keybinding:
  universal:
    scrollLeft: ""
    scrollRight: ""
    scrollUpMain-alt1: ""
    scrollDownMain-alt1: ""
    nextBlock-alt: ""
    prevBlock-alt: ""
    nextBlock: "J"
    prevBlock: "K"
    nextTab: "L"
    prevTab: "H"
git:
  commit:
    autoWrapWidth: 88
