keybinding:
  universal:
    scrollLeft: ""
    scrollRight: ""
    scrollUpMain-alt1: ""
    scrollDownMain-alt1: ""
    nextBlock-alt: ""
    prevBlock-alt: ""
    nextBlock: "J"
    prevBlock: "K"
    nextTab: "L"
    prevTab: "H"
git:
  commit:
    autoWrapWidth: 88
