keybinding:
  universal:
    appendNewline: "<c-n>"
    scrollLeft: null
    scrollRight: null
    scrollUpMain-alt1: null
    scrollDownMain-alt1: null
    nextBlock: "J"
    prevBlock: "K"
    nextTab: "L"
    prevTab: "H"
