[tool.poetry]
name = "poetry"
version = "0.1.0"
description = ""
authors = ["Uy Ha<hchanuy@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
ipython = "*"
cmake-language-server = "*"
pynvim = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
